
server:
  port: 8080
spring:
  application:
    name: lincensingservice
  profiles:
    active:
      default

  jpa:
    database: MYSQL
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
      ##validate      加载hibernate时，验证创建数据库表结构
      ##create        每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
      ##create-drop   加载hibernate时创建，退出是删除表结构
      ##update        加载hibernate自动更新数据库结构
      ##validate      启动时验证表的结构，不会创建表
      ##none          启动时不做任何操作
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 38433623
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**
